### PR TITLE
[*.py] Use `os.path.join`; fix typos; blacken; [*.rst => *.md] Pandoc; [README.md] Add shields

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by shx2** [comment]
Thank you for contributing.

This includes several unrelated changes.   I will comment on each:

- `os.path.join`, fix typos: ok. please submit a new PR for this only.
- blacken: while the advantages of this are understood, this is primarily a question of taste. I personally don't like it.
- [*.rst => *.md], Pandoc: please explain the motivation. how does this make the project better?
- [README.md] Add shields: ok. please submit a new PR for this only.

**Comment by SamuelMarks** [comment]
Wow that's a lot of PRs!

Okay I'll see what I can do…

On the pandoc side, .md is what GitHub recommends.

**Comment by SamuelMarks** [comment]
/closing this because other PRs have been opened from this—as requested—with everything but black

**Comment by shx2** [comment]
> On the pandoc side, .md is what GitHub recommends.

I was not aware of that...
Where? Can you give me a reference please?

**Comment by SamuelMarks** [comment]
Examples:
- https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax
- When you create a new repo on the web it lets you initiate with a README… that is in `.md` format
- Scroll through the list of popular GitHub repo and determine the trend. `.md` is tetrationally more popular than `.rst`

In terms of writing the files themselves, I found all these formats to be just as easy as one another. But conforming to the "GitHub standard" whilst publishing to GitHub does make sense. Even pypi now supports md…

**Pull request closed without merging**
