### PR TITLE
[*.py] Use `os.path.join`; fix typos

### PR DESCRIPTION
**Pull request by SamuelMarks**
As per #2, put this in a separate PR

### CODE REVIEW

**Comment by SamuelMarks** [comment]
@shx2 Not sure why there is such a large diff on this one, I didn't run `black`… it's most likely a whitespace issue. Would you accept a `.editoconfig` PR?

**Comment by shx2** [comment]
I'm sorry, I can't assess the diffs like that.

I believe the current state of whitespaces in this project is as desired, so please make an effort to preserve it. 

> Would you accept a .editoconfig PR?

Sure.  Thank you.  Please make sure it agrees with formats/whitespaces currently used in this project.

**Comment by SamuelMarks** [comment]
@shx - Oh actually it might just be line endings:
```
$ git clone https://github.com/shx2/apegears &>/dev/null
$ find apegears -type f -exec dos2unix {} \; &>/dev/null
$ GIT_WORK_TREE='apegears' GIT_DIR='apegears/.git' git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   apegears/func_argparse.py
	modified:   apegears/iofile.py
	modified:   apegears/lo99ing.py
	modified:   apegears/misc.py
	modified:   apegears/parser.py
	modified:   apegears/spec.py

no changes added to commit (use "git add" and/or "git commit -a")
```

(so of the 19 python files in your repo, 6 of them have DOS line-endings and 13 have UNIX line-endings)

**Comment by shx2** [comment]
You're Right!  My bad.

I fixed newlines in master now.  Please rebase your changes.

**Comment by SamuelMarks** [comment]
@shx2 +17 -16 ; that's better

**Pull request merged**
